[package]
name = "template"
version = "0.1.0"
authors = ["Yoep Kortekaas <y.a.m.kortekaas@student.utwente.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
